Test

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -39,18 +39,19 @@ jobs:
   tests-done:
     name: Tests Done
     runs-on: ubuntu-latest
-    if: ${{ always() }}
+    # if: ${{ always() }}
     needs: [run-tests]
     steps:
-      - run : echo "${{needs.run-tests.result}}" 
-      - run : |
-              if [[ ${{needs.run-tests.result}} =~ "failure" ]]; then
-                echo "All bad! 😠";
-                exit 1;
-              else
-                echo "All good! 😀";
-                exit 0;
-              fi
+        - run: echo 'All good!'
+      # - run : echo "${{needs.run-tests.result}}" 
+      # - run : |
+      #         if [[ ${{needs.run-tests.result}} =~ "failure" ]]; then
+      #           echo "All bad! 😠";
+      #           exit 1;
+      #         else
+      #           echo "All good! 😀";
+      #           exit 0;
+      #         fi
   deploy: 
     name: Deployment
     runs-on: ubuntu-latest
